version: '3.1'

services:
   db:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: password
     volumes:
        - dbdata:/var/lib/mysql
  adminer:
     image: adminer:latest
     ports:
       - 8080:8080
volumes:
    dbdata:
     driver: local