version: '3.4'

services:
  apache_httpd:
    image: httpd:latest
    deploy:
      mode: replicated
      replicas: 2
      labels:
        com.docker.descr: "test description"
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 50M
        reservations:
          cpus: '0.10'
      update_config:
        parallelism: 1
        delay: 10s
        monitor: 5s

