version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - db_adminer
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - db_adminer

networks:
  db_adminer:
    driver: bridge
